version: "3.7"

services:
  db:
    image: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: docker
    ports:
      - '5432:5432'
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./mysite:/code
    ports:
      - "8000:8000"
    depends_on:
      - db